### ISSUE TITLE
Install on CentOS7 minimal install fails

### ISSUE THREAD

**Issue by judouk** [kso512/install-check_mk-server#3]
I took a minimal install of CentOS and tried to install.
It failed so I modified the playbook accordingly but I suspect this needs updating to include the 'if yum' logic

Needs 'epel-release' and 'perl-Net-SNMP'

$ cat playbooks/install-check_mk-server.yaml 
- name: Playbook to configure Check_MK servers
  hosts: mycheckmkserver
  become: true
  pre_tasks:
    - name: Install prerequisite packages
      package:
        name: epel-release
        state: present
  roles:
  - role: ../roles/install-check_mk-server
    install_check_mk_server_site: mysite
    install_check_mk_server_prereqs:
      - perl-Net-SNMP

**Comment by kso512** [comment]
Hi judouk,

I created a new branch and added the two packages to the prereqs list for CentOS.

Can you switch to the [judouk-00001 branch](https://github.com/kso512/install-check_mk-server/tree/judouk-00001) and try again, letting me know how it goes?

Thanks,
- kso512

**Comment by judouk** [comment]
Sorry, thats not worked
epel-release must be installed before perl-Net-SNMP so I had to use the pre_tasks option.

As an FYI, I had to do quite a bit more to get this functional on a minimal CentOS7 install.

As selinux is enabled by default and it's more often recommended that this is left on, I also needed to install libsemanage-python

...and then of course I had to configure the firewall :(

  pre_tasks:
    - name: Install prerequisite packages
      package:
        name:
          - epel-release
          - libsemanage-python
        state: present
  tasks:
    - name: Configure firewall for Check_MK (tcp/80)
      firewalld:
        service: http
        permanent: yes
        state: enabled
    - name: Configure firewall for Check_MK (tcp/514)
      firewalld:
        port: 514/tcp
        permanent: yes
        state: enabled
    - name: Configure firewall for Check_MK (udp/514)
      firewalld:
        port: 514/udp
        permanent: yes
        state: enabled
    - name: Configure firewall for Check_MK (udp/162)
      firewalld:
        port: 162/udp
        permanent: yes
        state: enabled
    - name: Configure selinux
      seboolean:
        name: httpd_can_network_connect
        state: yes
        persistent: yes
    - name: Restart firewall
      service:
        name: firewalld
        state: restarted
  roles:
  - role: ../roles/install-check_mk-server

**Comment by kso512** [comment]
Hi judouk,

Per my understanding of Ansible best practices, those other tasks should be handled by other roles and not this one.

For example, EPEL can be installed with this excellent role:
https://galaxy.ansible.com/geerlingguy/repo-epel

There are others for managing selinux, firewalld, etc.

I will try to clear up these requirements in README.md, but I will not merge the judouk-00001 branch into master at this time, since the current version works for the CentOS 7 docker image I use for testing.

Thanks,
- kso512

**Comment by judouk** [comment]
Thanks for the explanation kso512
I was trying to use your recipe to build on a minimal installation so having the readme updated to include that additional repo's should be included would be great.

Thanks for your help
