### ISSUE TITLE
URL Update

### ISSUE THREAD

**Issue by m3rlinux** [kso512/install-check_mk-server#4]
Hi!
I notice you that the URL for downlading rpm is changed.
You need to update defaults vars to new one:

install_check_mk_server_source_url: https://checkmk.com/support//{{ install_check_mk_server_version }}/{{ install_check_mk_server_source }}

**Comment by kso512** [comment]
Hi m3rlinux,

Thanks for the issue!  I fixed this just now and it should be live soon.

[1.6.0p6 6bc1815] Change source URL to checkmk.com per m3rlinux

- kso512
